MOVIE_SITES = [
    {'name': '19影视', 'url': 'https://www.19kan.com/vodsearch.html?wd={0}', 'selector': 'body div.fed-main-info.fed-min-width div div div.fed-main-left.fed-col-xs12.fed-col-md9 div div.fed-part-layout.fed-back-whits.fed-margin-right dl'},
    {'name': '2TU影院', 'url': 'http://www.82tu.cc/search.php?searchword={0}', 'selector': 'ul.mlist div.info'},
    {'name': '52 Movie', 'url': 'http://www.52movieba.com/search.htm?keyword={0}', 'selector': 'table.table.table-hover.threadlist tr.thread.tap'},
    {'name': '592美剧', 'url': 'http://www.592meiju.com/search/?wd={0}', 'selector': 'ul.serach-ul div.info'},
    {'name': '66影视网', 'method': "post", 'url': 'https://www.66ys.tv/e/search/index.php', 'data': r'show=title%2Csmalltext&tempid=1&tbname=Article&keyboard=${gunititle}&Submit22=%E6%90%9C%E7%B4%A2', 'headers': {"Content-Type": "application/x-www-form-urlencoded" }, 'rewrite_href': True, 'selector': "div.listBox li"},
    {'name': '6V电影网', 'method': "post", 'url': 'http://www.6vhao.tv/e/search/index.php', 'data': r'show=title%2Csmalltext&tempid=1&tbname=Article&keyboard=${gunititle}&Submit22=%E6%90%9C%E7%B4%A2', 'headers': { "Content-Type": "application/x-www-form-urlencoded" }, 'rewrite_href': True, 'selector': "div.listBox li"},
    {'name': '8V电影网', 'url': 'http://www.8vdy.com/search.asp?searchword={0}', 'selector': '#div_2 div.listInfo'},
    {'name': '962电影网', 'url': 'http://www.fx962.com/search.asp?searchword={0}', 'selector': '#contents li'},
    {'name': '97电影网', 'url': 'http://www.55xia.com/search?q={0}', 'selector': 'p.movie-name a:contains({0})'},
    {'name': '9去这里', 'url': 'http://9qzl.com/index.php?s=/video/search/wd/{0}', 'selector': "ul.mov_list li"},
    {'name': 'BT先锋', 'url': 'https://btzhijia.com/s/{0}' + '.html', 'selector': 'div.right a.name'},
    {'name': 'CK电影', 'url': 'http://www.ck180.net/search.html?q={0}', 'selector': 'ul.serach-ul div.info'},
    {'name': 'LOL电影', 'url': 'http://www.993dy.com/index.php?m=vod-search&wd={0}', 'selector': 'div.movielist a.play-img'},
    {'name': 'MP4Vv', 'url': 'http://www.mp4pa.com/search.php?searchword={0}', 'selector': 'ul.list-unstyled h4.weixin'},
    {'name': 'MP4电影', 'url': 'http://www.domp4.com/search/{0}' + '-1.html', 'selector': 'div.vodlist_l.box div.play_info'},
    {'name': 'TL95', 'url': 'http://www.tl95.com/?s={0}', 'selector': 'li.entry-title > a:contains({0})'},
    {'name': '比特大雄', 'url': 'https://www.btdx8.com/?s={0}', 'selector': '#content div.post.clearfix'},
    {'name': '比特影视', 'url': 'https://www.bteye.com/search/{0}', 'selector': '#main div.item'},
    {'name': '第一电影网', 'url': 'https://www.001d.com/?s={0}', 'selector': 'div.mainleft div.info'},
    {'name': '电影港', 'method': "post", 'url': 'http://so.dygang.net/e/search/index.php', 'data': 'tempid=1&tbname=article&keyboard=${gunititle}&show=title%2Csmalltext&Submit=%CB%D1%CB%F7', 'headers': {"Content-Type": "application/x-www-form-urlencoded"}, 'rewrite_href': True, 'selector': "table[width='100%'][border='0'][cellspacing='0'][cellpadding='0'] a.classlinkclass"},
    {'name': '电影日志', 'url': 'http://www.dyrizhi.com/search?s={0}', 'selector': 'div.pure-g div.item'},
    {'name': '电影天堂', 'method': "post", 'url': 'https://www.dy2018.com/e/search/index.php', 'data': 'show=title%2Csmalltext&tempid=1&keyboard=${gunititle}&Submit=%C1%A2%BC%B4%CB%D1%CB%F7', 'headers': {"Content-Type": "application/x-www-form-urlencoded" }, 'rewrite_href': True, 'selector': 'div.co_content8 table'},
    {'name': '钉子电影', 'method': "post", 'url': 'http://www.dingziyy.com/q#search_{0}', 'data': 'keyword={0}', 'csrf': {'name': "_csrf", 'update': "data" }, 'headers': {"Content-Type": "application/x-www-form-urlencoded" }, 'selector': 'h4 > a:contains({0})' },
    {'name': '嘎嘎影视', 'url': 'http://www.gagays.xyz/movie/search?req%5Bkw%5D={0}', 'selector': '#movie-sub-cont-db div.large-movie-detail'},
    {'name': '高清888', 'url': 'https://www.gaoqing888.com/search?kw={0}', 'selector': 'div.wp-content div.video-row'},
    {'name': '高清MP4', 'url': 'http://www.mp4ba.com/index.php?m=vod-search&wd={0}', 'selector': '#data_list tr.alt1'},
    {'name': '高清电台', 'url': 'https://gaoqing.fm/s.php?q={0}', 'selector': '#result1 div.row'},
    {'name': '界绍部', 'url': 'http://www.jsb456.com/?s={0}', 'selector': '#content h2.title'},
    {'name': '就爱那片', 'method': "post", 'url': 'http://www.inapian.com/index.php?s=vod-search&wd={0}', 'data': 'wd={0}', 'headers': { "Content-Type": "application/x-www-form-urlencoded" }, 'rewrite_href': True, 'selector': 'div.sortcon div.minfo'},
    {'name': '看美剧', 'url': 'http://www.kanmeiju.net/index.php?s=/video/search/wd/{0}', 'selector': 'div.listri p.t'},
    {'name': '蓝光网', 'url': 'http://www.languang.co/?s={0}', 'selector': 'div.mi_cont li'},
    {'name': '老司机电影', 'url': 'http://www.xsjdy.net/search/?s={0}', 'selector': 'div.row div.row.list.shadow' },
    {'name': "乐赏电影", 'url': 'http://www.gscq.me/search.htm?keyword={0}', 'selector': 'div.media-body div.subject.break-all'},
    {'name': "两个BT", 'url': 'https://www.bttwo.com/?s={0}', 'selector': 'div.mi_cont h3.dytit'},
    {'name': '美剧仓库', 'method': "post", 'url': 'http://www.meijuck.com/e/search/index.php', 'data': 'show=title&tempid=1&tbname=news&mid=1&dopost=search&keyboard={0}&submit=', 'headers': {"Content-Type": "application/x-www-form-urlencoded"}, 'rewrite_href': True, 'selector': "div.content-wrap p.note"},
    {'name': "美剧汇", 'url': 'http://www.meijuhui.net/search.php?q={0}', 'selector': 'article.excerpt li.focus'},
    {'name': '美剧鸟', 'url': 'http://www.meijuniao.com/index.php?s=vod-search-wd-{0}' + '.html', 'headers': {"X-Requested-With": "XMLHttpRequest"}, 'ajax': "http://www.meijuniao.com/index.php?s=vod-search-wd-{0}" + "-1-ajax", 'type': "json", 'selector': 'data.count > 0'},
    {'name': '迷你MP4', 'url': 'http://www.minimp4.com/search?q={0}', 'selector': 'div.container div.col-xs-7'},
    {'name': '泡饭影视', 'url': 'http://www.chapaofan.com/search/{0}', 'selector': 'li a[title*={0}]'},
    {'name': '片吧', 'url': 'http://so.pianbar.com/search.aspx?q={0}', 'selector': 'h4.media-heading + span:contains({0})'},
    {'name': '飘花资源网', 'url': 'https://www.piaohua.com/plus/search.php?kwtype=0&keyword={0}', 'selector': 'div.container div.txt'},
    {'name': '人生05', 'url': 'http://www.rs05.com/search.php?s={0}', 'selector': '#movielist li'},
    {'name': '贪玩影视', 'url': 'http://www.tanwanyingshi.com/movie/search?keyword={0}', 'selector': 'div.service-content a:contains({0})'},
    {'name': '下片片', 'url': 'http://search.xiepp.com/search.aspx?q={0}', 'selector': 'div.searchlist h4.media-heading'},
    {'name': '新6V电影', 'method': "post", 'url': 'https://www.66s.cc/e/search/index.php', 'data': 'show=title&tempid=1&tbname=article&mid=1&dopost=search&submit=&keyboard={0}', 'headers': { "Content-Type": "application/x-www-form-urlencoded"}, 'rewrite_href': True, 'selector': '#post_container div.entry_post'},
    {'name': '新片网', 'url': 'http://www.91xinpian.com/index.php?m=vod-search&wd={0}', 'selector': 'div.search span.name'},
    {'name': '迅雷影天堂', 'url': 'https://www.xl720.com/?s={0}', 'selector': 'h3 a[title*={0}]'},
    {'name': '迅影网', 'url': 'http://www.xunyingwang.com/search?q={0}', 'selector': 'div.row p.movie-name'},
    {'name': '阳光电影', 'url': 'http://s.ygdy8.com/plus/so.php?kwtype=0&searchtype=title&keyword={0}', 'selector': "div.co_area2 table[border='0'][width='100%']"},
    {'name': '一只大榴莲', 'url': 'http://www.llduang.com/?s={0}', 'selector': 'div.mainleft div.info'},
    {'name': '音范丝', 'url': 'http://www.yinfans.com/?s={0}', 'selector': 'div.thumbnail a[title*={0}]' },
    {'name': '影海', 'url': 'http://www.yinghub.com/search/list.html?keyword={0}', 'selector': 'div.row div.info'},
    {'name': '影视看看', 'url': 'http://www.yskk.tv/index.php?m=vod-search&wd={0}', 'selector': 'div.movielist li' },
    {'name': '云播网', 'url': 'http://www.yunbowang.cn/index.php?m=vod-search&wd={0}', 'selector': 'div.container div.col-xs-7'},
    {'name': '中国高清网', 'url': 'http://gaoqing.la/?s={0}', 'selector': 'div.mainleft div.thumbnail'},
    {'name': '宅腐资源站', 'url': 'http://www.zhaifu.cc/plus/search.php?kwtype=0&q={0}', 'selector': 'div.content a.focus'},
    {'name': '最新影视站', 'url': 'http://www.zxysz.com/?s={0}', 'selector': '#content li.p-item'}
]