MOVIE_SITES = [
    {'name': '19影视', 'url': 'https://www.19kan.com/vodsearch.html?wd={0}', 'selector': 'dl.fed-list-deta', 'description': '可播放'},
    {'name': '2TU影院', 'url': 'http://www.82tu.cc/search.php?searchword={0}', 'selector': 'ul.mlist div.info', 'description': '可播放+可下载'},
    {'name': 'BT先锋', 'url': 'http://btzhijia.com/s/{0}' + '.html', 'selector': 'div.right a.name', 'description': '可播放+可下载'},
    {'name': 'LOL电影', 'url': 'http://www.993dy.com/index.php?m=vod-search&wd={0}', 'selector': 'div.movielist a.play-img', 'description': '可下载'},
    {'name': 'MP4Vv', 'url': 'http://www.mp4pa.com/search.php?searchword={0}', 'selector': 'ul.list-unstyled h4.weixin', 'description': '可下载'},
    {'name': 'MP4电影', 'url': 'http://www.domp4.com/search/{0}' + '-1.html', 'selector': 'div.vodlist_l.box div.play_info', 'description': '可下载'},
    {'name': '比特大雄', 'url': 'https://www.btdx8.com/?s={0}', 'selector': '#content div.post.clearfix', 'description': '可下载'},
    {'name': '比特影视', 'url': 'https://www.bteye.com/search/{0}', 'selector': '#main div.item', 'description': '可下载'},
    {'name': '第一电影网', 'url': 'https://www.001d.com/?s={0}', 'selector': 'div.mainleft div.info', 'description': '可下载'},
    {'name': '嘎嘎影视', 'url': 'http://www.gagays.xyz/movie/search?req%5Bkw%5D={0}', 'selector': '#movie-sub-cont-db div.large-movie-detail', 'description': '可下载'},
    {'name': '高清888', 'url': 'https://www.gaoqing888.com/search?kw={0}', 'selector': 'div.wp-content div.video-row', 'description': '可下载'},
    {'name': '高清MP4', 'url': 'http://www.mp4ba.com/index.php?m=vod-search&wd={0}', 'selector': '#data_list tr.alt1', 'description': '可下载'},
    {'name': '高清电台', 'url': 'https://gaoqing.fm/s.php?q={0}', 'selector': '#result1 div.row', 'description': '可下载'},
    {'name': '界绍部', 'url': 'http://www.jsb456.com/?s={0}', 'selector': '#content h2.title', 'description': '可下载'},
    {'name': '就爱那片', 'url': 'http://www.inapian.com/index.php?s=vod-search&wd={0}', 'selector': 'div.sortcon div.minfo', 'description': '可下载'},
    {'name': '看美剧', 'url': 'http://www.kanmeiju.net/index.php?s=/video/search/wd/{0}', 'selector': 'div.listri p.t', 'description': '可播放+可下载'},
    {'name': "乐赏电影", 'url': 'http://www.gscq.me/search.htm?keyword={0}', 'selector': 'div.media-body div.subject.break-all', 'description': '可下载'},
    {'name': "两个BT", 'url': 'https://www.bttwo.com/?s={0}', 'selector': 'div.mi_cont h3.dytit', 'description': '可播放+可下载'},
    {'name': "美剧汇", 'url': 'http://www.meijuhui.net/search.php?q={0}', 'selector': 'article.excerpt li.focus', 'description': '可播放+可下载'},
    # {'name': '美剧鸟', 'url': 'http://www.meijuniao.com/index.php?s=vod-search-wd-{0}' + '.html', 'selector': '#contents ul li', 'description': '可下载'},
    {'name': '泡饭影视', 'url': 'http://www.chapaofan.com/search/{0}', 'selector': 'div.content-list > div > ul.item', 'description': '可下载'},
    {'name': '飘花资源网', 'url': 'https://www.piaohua.com/plus/search.php?kwtype=0&keyword={0}', 'selector': 'div.container div.txt', 'description': '可下载'},
    {'name': '5号站', 'url': 'http://www.baike789.com/s/{0}/', 'selector': 'li.m_list', 'description': '可播放'},
    {'name': '贪玩影视', 'url': 'http://www.tanwanyingshi.com/movie/search?keyword={0}', 'selector': '.service-item', 'description': '', '可播放+可下载'},
    {'name': '新片网', 'url': 'http://www.91xinpian.com/index.php?m=vod-search&wd={0}', 'selector': 'div.search span.name', 'description': '可播放+可下载'},
    {'name': '迅雷影天堂', 'url': 'https://www.xl720.com/?s={0}', 'selector': 'div.post-grid div h3', 'description': '可播放'},
    {'name': '一只大榴莲', 'url': 'http://www.llduang.com/?s={0}', 'selector': 'div.mainleft div.info', 'description': '可下载'},
    {'name': '影视看看', 'url': 'http://www.yskk8.com/index.php?m=vod-search&wd={0}', 'selector': 'div.movielist li', 'description': '可播放+可下载'},
    # {'name': '云播网', 'url': 'http://www.yunbowang.cn/index.php?m=vod-search&wd={0}', 'selector': 'div.container div.col-xs-7', 'description': ''},
    {'name': '中国高清网', 'url': 'http://gaoqing.la/?s={0}', 'selector': 'div.mainleft div.thumbnail', 'description': '可下载'},
    {'name': '最新影视站', 'url': 'http://www.zxysz.com/?s={0}', 'selector': '#content li.p-item', 'description': '可下载'},
    {'name': '影海', 'url': 'http://www.yinghub.com/search/list.html?keyword={0}', 'selector': 'div.movie-list-item', 'description': '可下载'},
    # {'name': '52 Movie', 'url': 'http://www.52movieba.com/search.htm?keyword={0}', 'selector': 'table.table.table-hover.threadlist tr.thread.tap', 'description': ''},
    {'name': '蓝光网', 'url': 'http://www.languang.co/?s={0}', 'selector': 'div.mi_cont li', 'description': '可下载'},
    {'name': '片吧', 'url': 'http://so.pianbar.com/search.aspx?q={0}', 'selector': '.media', 'description': '可下载'},
    {'name': '下片片', 'url': 'http://search.xiepp.com/search.aspx?q={0}', 'selector': 'div.searchlist h4.media-heading', 'description': '可下载'},
    # {'name': '66影视网', 'url': 'http://www.66e.cc', 'selector': "div.listBox li", 'comment': 'post request', 'description': ''},
    # {'name': '6V电影网', 'url': 'http://www.6vhao.tv', 'selector': "div.listBox li", 'comment': 'post request', 'description': ''},
    # {'name': '8V电影网', 'url': 'http://www.8vdy.com', 'selector': '#div_2 div.listInfo', 'comment': 'post request', 'description': ''},
    # {'name': '电影天堂', 'url': 'https://www.dy2018.com', 'selector': 'div.co_content8 table', 'comment': 'post request', 'description': ''},
    # {'name': '钉子电影', 'url': 'http://www.dingziyy.com', 'selector': '.box-content', 'comment': 'post request', 'description': ''},
    # {'name': '美剧仓库', 'url': 'http://www.meijuck.com', 'selector': "div.content-wrap p.note", 'comment': 'post request', 'description': ''},
    # {'name': '新6V电影', 'url': 'https://www.66s.cc', 'selector': '#post_container div.entry_post', 'comment': 'post request', 'description': ''},
    # {'name': '9去这里', 'url': 'http://9qzl.com', 'selector': "ul.mov_list li", 'comment': 'post request', 'description': ''},
    # {'name': '天天云影院', 'url': 'http://www.ttyyy.vip/index.html', 'selector': '#yun-list li', 'comment': 'post request', 'description': ''},
    # {'name': '六六电影网', 'url': 'http://www.6z6y.com', 'selector': '#contents li', 'comment': 'post request', 'description': ''},
]